"""Added password and marketing to user table

Revision ID: 15b1b0aae443
Revises: ea4a48e70de8
Create Date: 2025-11-13 11:46:09.412434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b1b0aae443'
down_revision = 'ea4a48e70de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('marketing_opt_in', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('marketing_opt_in')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
